[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/api/food/*"
  to = "/.netlify/functions/food-proxy"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
